version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: gotopup_db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: gotopup
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5656:5432"
    networks:
      - postgres_network

volumes:
  db_data:

networks:
  postgres_network:
    driver: bridge
